### ISSUE TITLE
ubuntu20.04 不支持 吗？

### ISSUE THREAD

**Issue by JoeyZhu** [soulteary/apt-proxy#18]
在ubuntu20.04嵌入式系统里面安装包时出错：

`2023/02/19 10:43:07 running apt-proxy 
2023/02/19 10:43:08 Start benchmarking mirrors
2023/02/19 10:43:08 Finished benchmarking mirrors
2023/02/19 10:43:08 using fastest Ubuntu mirror http://mirrors.aliyun.com/ubuntu/
2023/02/19 10:43:08 Start benchmarking mirrors
2023/02/19 10:43:08 Finished benchmarking mirrors
2023/02/19 10:43:08 using fastest Debian mirror https://repo.huaweicloud.com/debian/
2023/02/19 10:43:08 Start benchmarking mirrors
2023/02/19 10:43:08 Finished benchmarking mirrors
2023/02/19 10:43:08 using fastest CentOS mirror http://mirrors.aliyun.com/centos/
2023/02/19 10:43:08 Start benchmarking mirrors
2023/02/19 10:43:08 Finished benchmarking mirrors
2023/02/19 10:43:08 using fastest Alpine mirror http://mirrors.aliyun.com/alpine/
2023/02/19 10:43:08 proxy listening on 0.0.0.0:3142
2023/02/19 10:43:08 Program has been started 🚀
2023/02/19 10:47:53 http: superfluous response.WriteHeader call from github.com/soulteary/apt-proxy/internal/server.(*responseWriter).WriteHeader (proxy.go:120)
2023/02/19 10:47:53 192.168.2.231 "GET http://ports.ubuntu.com/pool/main/p/python3.8/libpython3.8_3.8.10-0ubuntu1%7e20.04.5_arm64.deb HTTP/1.1" (Not Found) 0 [33;1mSKIP[0m 504.877717ms
panic: net/http: abort Handler

goroutine 745 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0005970e0, {0x79efb8?, 0xc0005063c0}, 0xc00028c000)
	/opt/hostedtoolcache/go/1.19.3/x64/src/net/http/httputil/reverseproxy.go:363 +0xee9
github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream.func1()
	/home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:253 +0x3d
created by github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream
	/home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:252 +0x1fb`

本机的source.list：
joey@v3dd120:~$ cat /etc/apt/sources.list
deb http://ports.ubuntu.com/ focal main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-security main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-security main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-updates main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-updates main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-backports main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-backports main restricted universe multiverse

运行的命令：
sudo http_proxy=http://192.168.2.171:3142 apt-get -o pkgProblemResolver=true -o Acquire::http=true install tmux

**Comment by soulteary** [comment]
你使用的是 ARMv64 版本的系统，可以使用参数：`--mode=ubuntu-ports --ubuntu-ports=cn:tsinghua`

功能更新于  https://github.com/soulteary/apt-proxy/releases/tag/v0.6.0 版本
