### ISSUE TITLE
请问docker版本的image如何增加源地址？ 

### ISSUE THREAD

**Issue by yexingqi** [soulteary/apt-proxy#20]
请问docker版本的image如何增加源地址？  谢谢！！
docker run -d --name=apt-proxy -p 3142:3142 soulteary/apt-proxy  
我想单独增加ubuntu 或centos的源，请问有什么方法么？

**Comment by soulteary** [comment]
https://github.com/soulteary/apt-proxy?tab=readme-ov-file#mirror-configuration

指定源地址即可
