### ISSUE TITLE
设置的代理没有预期加速

### ISSUE THREAD

**Issue by rayblade** [soulteary/apt-proxy#9]
通过二进制方式使用 APT Proxy和使用docker方式部署，在另外一个docker中运行http_proxy=http://IP:3142 apt-get -o pkgProblemResolver=true -o Acquire::http=true update，日志显示：
2022/06/27 11:46:55 running apt-proxy 
2022/06/27 11:46:55 Start benchmarking mirrors
2022/06/27 11:46:55 Finished benchmarking mirrors
2022/06/27 11:46:55 using fastest mirror http://mirrors.ustc.edu.cn/debian/
2022/06/27 11:46:56 Start benchmarking mirrors
2022/06/27 11:46:56 Finished benchmarking mirrors
2022/06/27 11:46:56 using fastest mirror https://mirrors.ustc.edu.cn/ubuntu/
2022/06/27 11:46:56 proxy listening on 0.0.0.0:3142
2022/06/27 13:11:06 rewrote "http://security.debian.org/debian-security/dists/bullseye-security/InRelease" to "http://security.debian.org/debian-security/dists/bullseye-security/InRelease"
2022/06/27 13:11:06 rewrote "http://deb.debian.org/debian/dists/bullseye/InRelease" to "http://deb.debian.org/debian/dists/bullseye/InRelease"
2022/06/27 13:11:08 172.17.0.1 "GET http://security.debian.org/debian-security/dists/bullseye-security/InRelease HTTP/1.1" (OK) 44101 MISS 2.053085892s

rewrote没有更改为加速的地址，并且在ctrl+c强行中断update后，APT Proxy会意外退出，日志显示：

2022/06/27 13:11:33 rewrote "http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/by-hash/SHA256/2a871a690d15b95aa9403081f150d8b6309628eb85228642450cb9d408a0759d" to "http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/by-hash/SHA256/2a871a690d15b95aa9403081f150d8b6309628eb85228642450cb9d408a0759d"
panic: net/http: abort Handler

goroutine 358 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0000501e0, {0x782190?, 0xc0001b6f60}, 0xc0001b2400)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/httputil/reverseproxy.go:349 +0xe89
github.com/soulteary/apt-proxy/pkgs/httpcache.(*Handler).passUpstream.func1()
	/home/runner/work/apt-proxy/apt-proxy/pkgs/httpcache/handler.go:254 +0x3d
created by github.com/soulteary/apt-proxy/pkgs/httpcache.(*Handler).passUpstream
	/home/runner/work/apt-proxy/apt-proxy/pkgs/httpcache/handler.go:253 +0x1fb

**Comment by soulteary** [comment]
可以试试 0.3.3，我本地测试没啥问题啦 :D @rayblade 

```bash
docker pull soulteary/apt-proxy
```

使用 docker pull 更新镜像，然后重新运行即可。
